/**
 * Text-to-Speech API
 * A simple API for converting text to speech.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ritlabs1404@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Error from './model/Error';
import Success from './model/Success';
import TtsRequest from './model/TtsRequest';
import TtsResponse from './model/TtsResponse';
import TtsResponseData from './model/TtsResponseData';
import DefaultApi from './api/DefaultApi';


/**
* A simple API for converting text to speech..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TextToSpeechApi = require('index'); // See note below*.
* var xxxSvc = new TextToSpeechApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TextToSpeechApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TextToSpeechApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TextToSpeechApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Success model constructor.
     * @property {module:model/Success}
     */
    Success,

    /**
     * The TtsRequest model constructor.
     * @property {module:model/TtsRequest}
     */
    TtsRequest,

    /**
     * The TtsResponse model constructor.
     * @property {module:model/TtsResponse}
     */
    TtsResponse,

    /**
     * The TtsResponseData model constructor.
     * @property {module:model/TtsResponseData}
     */
    TtsResponseData,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
