/**
 * Text-to-Speech API
 * A simple API for converting text to speech.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ritlabs1404@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TextToSpeechApi);
  }
}(this, function(expect, TextToSpeechApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TextToSpeechApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('joinMP3Files', function() {
      it('should call joinMP3Files successfully', function(done) {
        //uncomment below and update the code to test joinMP3Files
        //instance.joinMP3Files(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readTextToSpeech', function() {
      it('should call readTextToSpeech successfully', function(done) {
        //uncomment below and update the code to test readTextToSpeech
        //instance.readTextToSpeech(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('textToSpeech', function() {
      it('should call textToSpeech successfully', function(done) {
        //uncomment below and update the code to test textToSpeech
        //instance.textToSpeech(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
