/**
 * PDF API
 * A simple API for processing PDF.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ritlabs1404@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SummarizeResponseData from './SummarizeResponseData';

/**
 * The SummarizeResponse model module.
 * @module model/SummarizeResponse
 * @version 1.0.0
 */
class SummarizeResponse {
    /**
     * Constructs a new <code>SummarizeResponse</code>.
     * @alias module:model/SummarizeResponse
     */
    constructor() { 
        
        SummarizeResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SummarizeResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SummarizeResponse} obj Optional instance to populate.
     * @return {module:model/SummarizeResponse} The populated <code>SummarizeResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SummarizeResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = SummarizeResponseData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SummarizeResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SummarizeResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          SummarizeResponseData.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/SummarizeResponseData} data
 */
SummarizeResponse.prototype['data'] = undefined;






export default SummarizeResponse;

