/**
 * PDF API
 * A simple API for processing PDF.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ritlabs1404@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SummarizeResponseData model module.
 * @module model/SummarizeResponseData
 * @version 1.0.0
 */
class SummarizeResponseData {
    /**
     * Constructs a new <code>SummarizeResponseData</code>.
     * @alias module:model/SummarizeResponseData
     */
    constructor() { 
        
        SummarizeResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SummarizeResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SummarizeResponseData} obj Optional instance to populate.
     * @return {module:model/SummarizeResponseData} The populated <code>SummarizeResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SummarizeResponseData();

            if (data.hasOwnProperty('output')) {
                obj['output'] = ApiClient.convertToType(data['output'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SummarizeResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SummarizeResponseData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['output'] && !(typeof data['output'] === 'string' || data['output'] instanceof String)) {
            throw new Error("Expected the field `output` to be a primitive type in the JSON string but got " + data['output']);
        }

        return true;
    }


}



/**
 * @member {String} output
 */
SummarizeResponseData.prototype['output'] = undefined;






export default SummarizeResponseData;

