/**
 * PDF API
 * A simple API for processing PDF.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ritlabs1404@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TtsResponseData from './TtsResponseData';

/**
 * The TtsResponse model module.
 * @module model/TtsResponse
 * @version 1.0.0
 */
class TtsResponse {
    /**
     * Constructs a new <code>TtsResponse</code>.
     * @alias module:model/TtsResponse
     */
    constructor() { 
        
        TtsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TtsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TtsResponse} obj Optional instance to populate.
     * @return {module:model/TtsResponse} The populated <code>TtsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TtsResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = TtsResponseData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TtsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TtsResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          TtsResponseData.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/TtsResponseData} data
 */
TtsResponse.prototype['data'] = undefined;






export default TtsResponse;

